services:
  backend:
    build: ./
    image: news-app-be
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/news-app-be
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
